# Generated by Django 3.2 on 2023-07-26 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carMake', '0002_auto_20230721_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclemake',
            name='is_car',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vehiclemake',
            name='is_motor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehiclemake',
            name='is_tractor',
            field=models.BooleanField(default=False),
        ),
    ]
