# Generated by Django 3.2 on 2023-07-26 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carMake', '0004_auto_20230726_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclemake',
            name='is_car',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='vehiclemake',
            name='is_motor',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='vehiclemake',
            name='is_tractor',
            field=models.BooleanField(default=False),
        ),
    ]
